version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master --expect-workers 2

  worker1:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master

  worker2:
    image: locustio/locust
    volumes:
     - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master

    
    # Run example on windows:
    # docker run -p 8089:8089 --mount type=bind,source=C:\GitRepos\py\locust,target=/mnt/locust locustio/locust -f /mnt/locust/locustfile.py

    # Run headless:
    # docker run -p 8089:8089 --mount type=bind,source=C:\GitRepos\py\locust,target=/mnt/locust locustio/locust -f /mnt/locust/locustfile.py
    # --html /mnt/locust/myrun1.html --headless --only-summary -r 1 -u 1 -t 10s